export const girlWithMoney = 'src/assets/main/Backgrounds/GirlWithMoney.png'
export const mainTariffsBlockDelimiter = 'src/assets/main/Delimiters/Delimiter.svg'
export const mainAdvantagesBlockDelimiter = 'src/assets/main/Delimiters/Delimiter2.svg'
export const mainTariffsListCardBasic = 'src/assets/main/ListCard/Basic.png'
export const mainTariffsListCardStandard = 'src/assets/main/ListCard/Standard.png'
export const mainTariffsListCardPremium = 'src/assets/main/ListCard/Premium.png'